# -*- coding: utf-8 -*-
"""Lang_Chain - Lang Graph.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n-OODif6J7xAvSjBxoVBuB5zFCtJH0ZY
"""

#setup
from langraph.graph import StateGraph, END
from langchain_core.runnables import RunnableLambda
from typing import TypeDict

"""Text"""

#state
class State(TypeDict):
  message str

#Function

def start_node(state):
  print("Start")
  return {"message": "Let's Start"}

def process_node(state):
  print("Processing:", state["message"])
  return {"message": state["message"]+ "Now, we are processing"}

def end_node(state):
  print("End", State["message"])
  return state