# -*- coding: utf-8 -*-
"""Lang_Chain - Lang Graph 11/05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ROL5-jcTsn-23Z9HMspeOUX8xbb-k8H9
"""

#setup
from langraph.graph import StateGraph, END
from langchain_core.runnables import RunnableLambda
from typing import TypeDict

"""Text"""

#state
class State(TypeDict):
  message str

#Function

def start_node(state):
  print("Start")
  return {"message": "Let's Start"}

def process_node(state):
  print("Processing:", state["message"])
  return {"message": state["message"]+ "Now, we are processing"}

def end_node(state):
  print("End", State["message"])
  return state

#Graph
graph= StateGraph(state)
graph.add_node("start", RunnableLambda(start_node))
graph.add_node("process", RunnableLambda(process_node))
graph.add_node("end", RunnableLambda(end_node))